services:
  sciresearcher:
    build: .
    image: sciresearcher:latest
    container_name: sciresearcher

    environment:
      - MODELSCOPE_BASE_URL=${MODELSCOPE_BASE_URL:-https://api-inference.modelscope.cn/v1}
      - MODELSCOPE_API_KEY=${MODELSCOPE_API_KEY}
      - MINERU_API_TOKEN=${MINERU_API_TOKEN}

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    ports:
      - "7860:7860"  # Gradio Web端口

    stdin_open: true
    tty: true
